# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7cc8e3a2198544e4540b2e50ae3632ab1ec239859d3a97b6d9cdf41b61f75743a24e3a388580bdac4e9bd2d42b82a38acb5edd7ff8227248e1be48a8837f19

test:
  secret_key_base: 74356d1453d6ce8e9b0c440d2f671c361c5d046aba363050c8a468dfe69808489ef052f8a6f06ab4f93c60e8e06fdffd9d8f193f11177c1caceb684f6c19c8e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
